// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVHGaxZe1I4eMBc0z2hvdCsxIGAjo7Njs',
    appId: '1:437866758143:web:014ceabdffec168b6031ca',
    messagingSenderId: '437866758143',
    projectId: 'mentor-hub-c73d2',
    authDomain: 'mentor-hub-c73d2.firebaseapp.com',
    storageBucket: 'mentor-hub-c73d2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDrkjdhGx-uXz2lF6C9wzSFeXMfSdQ5QE',
    appId: '1:437866758143:android:3e4024560aadc3c56031ca',
    messagingSenderId: '437866758143',
    projectId: 'mentor-hub-c73d2',
    storageBucket: 'mentor-hub-c73d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVf-uV3JK3XcwwRa6e1bif8Pb_8mjqqfI',
    appId: '1:437866758143:ios:0949a1e13dbfe5ad6031ca',
    messagingSenderId: '437866758143',
    projectId: 'mentor-hub-c73d2',
    storageBucket: 'mentor-hub-c73d2.firebasestorage.app',
    iosBundleId: 'com.example.mentorHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVf-uV3JK3XcwwRa6e1bif8Pb_8mjqqfI',
    appId: '1:437866758143:ios:0949a1e13dbfe5ad6031ca',
    messagingSenderId: '437866758143',
    projectId: 'mentor-hub-c73d2',
    storageBucket: 'mentor-hub-c73d2.firebasestorage.app',
    iosBundleId: 'com.example.mentorHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVHGaxZe1I4eMBc0z2hvdCsxIGAjo7Njs',
    appId: '1:437866758143:web:460c0081a50cfd1f6031ca',
    messagingSenderId: '437866758143',
    projectId: 'mentor-hub-c73d2',
    authDomain: 'mentor-hub-c73d2.firebaseapp.com',
    storageBucket: 'mentor-hub-c73d2.firebasestorage.app',
  );
}
